### ISSUE TITLE
As a (potential) user, I want to understand what is being linted

### ISSUE THREAD

**Issue by afeld** [corbaltcode/opencontrol-linter#2]
Curious as to what the linting is checking for. Might be useful to include a few bullets about the kinds of things that are being checked for, so that I know if it would be helpful to me or not. Thanks!

**Comment by adriankierman** [comment]
Do you mean documenting something like this in our Readme

Linter currently checks for
- Schema Compliance with the OpenControl schema standards
  - Components 1.0, 2.0, 3.0, 3.1
  - Standards 1.0
  - Certifications 1.0
  - Manifest (opencontrol.yaml) 1.0
- Missing a required item in a manifest, component, standard or certification file
- Additional items that are not allowed according to the schema you specify
- Incorrect or misspelled items in required enumerations
- Broken links to your components
- Incorrectly specified schema version
- Missing OpenControl files
- and others

**Comment by afeld** [comment]
Exactly!

**Comment by adriankierman** [comment]
Merged in the above Readme.
